### ISSUE TITLE
When "main" matches source and "browser" field set, bundle fails.

### ISSUE THREAD

**Issue by benwiley4000** [browserify/browserify#1746] opened 2017-07-13 15:32 UTC
Using browserify 14.4.0. masOS Sierra.

Quite a weird repro. When running this command:
```bash
browserify module.js -o dist/module.js
```
And under this set of circumstances:
* The `"main"` field in package.json matches the source file (`"module.js"`)
* The `"browser"` field is also set (with any value, but in our case `"dist/module.js"`)

We get this error when bundling:
```bash
Error: module not found: "/<pathroot>/module/module.js" from file /<pathroot>/module/_fake.js
```

Changing the `"main"` field to something else allows browserify to succeed. Removing the `"browser"` field also works. Of course these aren't options for distribution.

**Comment by benwiley4000** [comment] 2017-07-13 16:28
After some simple A/B testing it appears to me this issue was introduced by [v14.1.0](https://github.com/substack/node-browserify/compare/14.0.0...14.1.0).

**Comment by benwiley4000** [comment] 2017-07-13 18:17
The error above is emitted by the readonly stream returned by `b.bundle()`.

If I change [this line](https://github.com/substack/node-browserify/blob/master/bin/cmd.js#L64):

```javascript
bundle.pipe(fs.createWriteStream(tmpfile));
```
to:
```javascript
bundle.pipe(fs.createWriteStream(outfile));
```
and comment out this [this line](https://github.com/substack/node-browserify/blob/master/bin/cmd.js#L57):
```javascript
// bundle.on('end', successExit);
```
I have no issues.

Maybe at some stage the pipeline is expecting the stream to be written to a file matching the specified `outfile`?

I've had trouble finding why the `"main"` and `"browser"` fields in package.json would affect this.

**Comment by benwiley4000** [comment] 2017-08-27 18:57
I'd love to see some additional heads looking at this issue. It's quite a serious problem for browser-targeted distribution of a module written using ES2015+ syntax.

Since the syntax is fully supported in recent Node versions I don't want to point `main` to a transpiled copy, yet I also need a `browser` entry for the web.

**Comment by ljharb** [comment] 2017-08-27 19:01
You should always point "main" to a CJS ES5 copy; that's not going to change.

**Comment by benwiley4000** [comment] 2017-08-27 19:09
Sorry, I actually wasn't precise about (or actually stated wrongly) the issue: I want to be able to include a bundled copy of my library as the `browser` entry (separate from the `main` entry). For some reason browserify is no longer accommodating for the case where the `main` entry of an npm package is the browserify source and the `browser` entry is the browserify target.

This actually isn't related to ES2015 (which should work fine with `require` on the Node side). I've experienced this same problem with an ES5 module. In the case of my ES2015 library, browserify is also running babelify.

**Comment by ljharb** [comment] 2017-08-27 20:02
Right, gotcha.

so you're saying if you did `browserify module.js -o dist/module2.js` (and set the package.json fields) it'd work? ie, is it just that the base filename is the same that's causing the problem?

**Comment by benwiley4000** [comment] 2017-08-27 20:30
Correct, I think. If I have:
```json
  "main": "module.js",
  "browser": "dist/module2.js",
```
and run the above, I have a problem.
If I delete or change either `main` or `browser` in my package.json, the problem disappears.

**Comment by smoke** [comment] 2018-05-15 11:31
Any news with that? 
With Angular 6 upgrade and the fact that it now requires browser specific builds to be pointed with the `browser` property in `package.json` this issue here is more relevant than ever (see https://github.com/angular/angular-cli/issues/10844#issuecomment-388841106).

For example I have been trying to set the property so that I can fix https://github.com/dtjohnson/xlsx-populate/issues/130 but I have no luck.

What happens is the following: When `browserify@16.2.2` starts to build the `xlsx-populate` it sees that there is `browser` property in the package.json and uses the pointed sources, so no fresh build is produced. If I delete the files `browser/xlsx-populate*` then it throws:

```
smoke@rkirilov-work-pc /home/smoke/xlsx-populate $ ./node_modules/.bin/gulp browser
[14:14:59] Using gulpfile /home/smoke/xlsx-populate/gulpfile.js
[14:14:59] Starting 'blank'...
[14:14:59] Finished 'blank' after 4.04 ms
[14:14:59] Starting 'browser-full'...
[14:14:59] Starting 'browser-no-encryption'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: module not found: "/home/smoke/xlsx-populate/lib/XlsxPopulate.js" from file /home/smoke/xlsx-populate/lib/_fake.js
    at onresolve (/home/smoke/xlsx-populate/node_modules/module-deps/index.js:181:30)
    at /home/smoke/xlsx-populate/node_modules/browserify/index.js:530:20
    at /home/smoke/xlsx-populate/node_modules/browser-resolve/index.js:247:21
    at /home/smoke/xlsx-populate/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/home/smoke/xlsx-populate/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/smoke/xlsx-populate/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/smoke/xlsx-populate/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by goto-bus-stop** [comment] 2018-05-15 12:36
It looks like browserify or browser-resolve replaces the path matching the `main` field (eg. `/xls-populate/lib/XlsxPopulate.js`) by the path in the `browser` field (`browser/xlsx-populateXXX.js`) in some situations. https://github.com/browserify/browserify/pull/1834 reproduces the problem.

**Comment by scottrippey** [comment] 2018-11-30 18:55
I'm having this issue too.  I can confirm that the steps to repro are simple:
```
{
  "main": "index.js",
  "browser": "browser.js",
  "scripts": {
    "build": "browserify index.js -o browser.js"
  }
}
```

This seems like a pretty common setup, right?

Anyway, I found a workaround:
```
"build": "cp index.js browser.js && browserify browser.js -o browser.js"
```
I'm making a copy of `index.js`, so that the filename doesn't match the `main` entry, and then use that as the input to `browserify`.
Also, instead of copying to a temp file, I'm just using the same filename as the final output, and it works just fine.

Hopefully this helps others, until a fix is implemented.

**Comment by stevenvachon** [comment] 2019-04-22 20:45
Both of my files are CommonJS modules, but I still experience this error.

**Comment by ArturoRis** [comment] 2019-07-22 00:20
I have just encountered this problem with `browserify v16.3.0`

@scottrippey your workaround is great :)

**Comment by goto-bus-stop** [comment] 2019-07-22 07:29
@stevenvachon 
> Both of my files are CommonJS modules, but I still experience this error.

When you do `browserify lib`, your browser field maps `lib` to `lib-es5`.

I'll close this since it's actually the correct behaviour.

**Closed by goto-bus-stop** 2019-07-22 07:29 UTC
