### ISSUE TITLE
Object spread fails with unexpected token

### ISSUE THREAD

**Issue by jvanveen** [browserify/browserify#1729] opened 2017-05-23 07:20 UTC
spread/rest doesn't seem to work:
```
let foo = {somevar: 'test'}
let bar = {test: 'test'}
let baz = {...foo, ...bar}
```
browserify foo.js

```
foo.js:3
let baz = {...foo, ...bar}
           ^
ParseError: Unexpected token
```

**Comment by zdychacek** [comment] 2017-07-19 07:36
Hi,

this issue is caused by underlying `acorn` parser which does not support this syntax feature currently.

Just now, you have tree choices how to solve this issue:

* wait till `acorn` supports this syntax
* patch `acorn` with `https://github.com/UXtemple/acorn-object-spread`
* use this fork, which use `babylon` as the parser under the hood: https://github.com/zdychacek/node-browserify. And then run this command: `$ browserify-babylon src/app.js -o dist/out.js -t [ babelify ] --parser-plugins [ objectRestSpread ]`

**Comment by goto-bus-stop** [comment] 2018-01-04 10:03
fixed by https://github.com/browserify/browserify/commit/7c3e585a83050f28291efc2dbd2407582cc5beb4, which includes this patch: https://github.com/browserify/detective/commit/c1e42dae473479394da5c6f5a79ad7b422a22fae

**Closed by goto-bus-stop** 2018-01-04 10:03 UTC
