### ISSUE TITLE
Exclude option not working using Gulp

### ISSUE THREAD

**Issue by benjclark** [browserify/browserify#1697] opened 2017-03-08 13:58 UTC
`exampleModuleName` is not being excluded in the output bundle via the following:

```
gulp.task('js', () => {
    return gulp.src('src/main/web/js/*.js')
    .pipe(tap(file => {
        file.contents = browserify(file.path, {
            debug: true,
            exclude: 'exampleModuleName'
        })
            .bundle();
    }))
    // .pipe other gulp tasks here
    .pipe(gulp.dest('public'))
});
```

I have tried `exclude: 'exampleModuleName'`, `exclude: '${folder.src}/js/exampleModuleName.js'`, `exclude: '**/exampleModuleName.js'` but no luck.

[Gulp-tap](https://github.com/geejs/gulp-tap) allows you to access the files in the stream as they are piped in.

Our ultimate goal to use the exclude option to exclude all of our app modules, leaving only vendor modules. This is the opposite of the existing option `bundleExternal = false` which we use to bundle only our app modules. If anyone has any suggestions please do share.

Thanks

**Comment by kolya-ay** [comment] 2017-03-08 18:08
It [seems that](https://github.com/substack/node-browserify/blob/fe8c57b86c586a3625257871e370fc6f278d1df5/index.js#L86-L101) browserify doesn't allow to pass `exclude` to `opts`. Try to

```js
 file.contents = browserify(file.path, {
            debug: true
        }).exclude('exampleModuleName').bunde()
```
The same inconvenience is issued here #1696

**Comment by goto-bus-stop** [comment] 2017-09-25 09:56
closing as duplicate of #1696. thanks!

**Closed by goto-bus-stop** 2017-09-25 09:56 UTC
