### ISSUE TITLE
browserifysearch.org link from readme is dead

### ISSUE THREAD

**Issue by binarykitchen** [browserify/browserify#1744] opened 2017-07-12 10:19 UTC
there is the link to http://browserifysearch.org/ in your readme which seems to be dead

```
└─( 2 ) ❱❱❱ ping http://browserifysearch.org/      
ping: http://browserifysearch.org/: Name or service not known
```

**Comment by goto-bus-stop** [comment] 2017-09-24 10:31
yep, it is. closing as a duplicate of #1718. thanks for reporting!

**Closed by goto-bus-stop** 2017-09-24 10:31 UTC
