### ISSUE TITLE
@substack, @everyone, when does browserify support es6+ import/export mudule?

### ISSUE THREAD

**Issue by anlexN** [browserify/browserify#1761] opened 2017-09-08 06:38 UTC

**Comment by emoticon** [comment] 2017-09-09 18:29
Just use Babel

**Comment by casr** [comment] 2017-09-24 10:12
It is likely to happen after Node starts to officially support it as that is what Browserify aims to emulate (aka “Node for the browser”). Only recently has Node 8.5 learned the flag `--experimental-modules`.

When the Node implementation is settled then you might expect a Browserify core to follow. As @emoticon mentions, you can use [Babelify](https://github.com/babel/babelify) today.

**Comment by jshnaidman** [comment] 2017-11-11 04:57
If I use babelify will the import keyword work properly? I read from the main page that

> browserify will recursively analyze all the require() calls in your app in order to build a bundle you can serve up to the browser in a single <script> tag.

Does that mean if you don't use require() it won't be included in the bundle?

**Comment by casr** [comment] 2017-11-11 10:06
Babelify is able to translate `import`/`export` statements to be CommonJS friendly which is what Browserify then uses at the bundling stage.

Very minimal example that will just translate `import`/`export` statements:
```sh
npm install browserify babelify babel-core babel-plugin-transform-es2015-modules-commonjs
```

`./.babelrc`:
```json
{
  "plugins": [
    "transform-es2015-modules-commonjs"
  ]
}
```

`./index.js`
```js
import events from 'events'
```

And then finally bundle it:
```sh
./node_modules/.bin/browserify -t babelify index.js
```

Browserify happily parses the rest of ES2015 so if your target environment supports this then all you need is the ES modules translation above.

**Comment by goto-bus-stop** [comment] 2017-11-23 16:22
as @casr mentioned you can use babelify for now to ~approach ES modules. otherwise closing as a duplicate of https://github.com/browserify/browserify/issues/1186

**Closed by goto-bus-stop** 2017-11-23 16:22 UTC
