### ISSUE TITLE
Browserify bundle contains absolute link to some development files

### ISSUE THREAD

**Issue by dominickp** [browserify/browserify#1571] opened 2016-06-02 17:38 UTC
I'm trying to bundle my CLI app with browserify (13.0.1) to make it easy to distribute, but I'm running into some issues with some (4 in particular) paths within the created bundle which contain absolute links to npm packages on my development environment. If I run the bundle from another machine, it can't find those resources.

Here is what I'm running:

`browserify ./src/js/cmd/interface.js > ./dist/test.js --node --dg`

// test.js
Line 52285
`}).call(this,"/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/node_modules/pug/node_modules/pug-filters/node_modules/clean-css/node_modules/source-map/node_modules/amdefine/amdefine.js")
`
Line 75816
`}).call(this,"/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/node_modules/yargs/lib")
`
Line 84494
`}).call(this,"/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/node_modules/yargs")
`
Line 85470
`}).call(this,"/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/src/js")
`

Is there any way to prevent this?

**Comment by jmm** [comment] 2016-06-05 21:50
Hi @dominickp. I'm going to take a guess that this may be related to using the `--no-commondir` option that is implied by `--node` / `--bare`. I suggest you try using the specific options that equate to `--node`, excluding `--no-commondir`, and see if that has the desired effect. Please provide a minimal reproduction to keep the issue open, or report back if that works and close the issue if it's resolved.

BTW when posting code like this, please mark it up as a block instead of inline code. See [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify#formatting) (and also the *example* section) for more information. Thanks!

**Comment by dominickp** [comment] 2016-06-07 15:21
Thanks for the reply. I retried with the following but the same lines are causing errors, except now they are relative paths which do not resolve.

```
$ browserify ./src/js/cmd/interface.js > ./dist/test.js --no-builtins --insert-global-vars="__filename,__dirname" --no-browser-field --dg
$ node ./dist/test.js --version
fs.js:839
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/node_modules'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.realpathSync (fs.js:1439:21)
    at /Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/dist/test.js:29859:38
    at Array.map (native)
    at Object.<anonymous> (/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/dist/test.js:29858:3)
    at Object.__dirname.150.fs (/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/dist/test.js:29989:4)
    at s (/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/dist/test.js:1:316)
    at /Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/dist/test.js:1:367
    at Object.__dirname.134../shared (/Users/dominickpeluso/Desktop/Shawmut/VDPBuddy1/dist/test.js:26835:16)

```

To reproduce, please clone this: https://github.com/shawmut/DataPreflight. Then run :
```
$ browserify ./src/js/cmd/interface.js > ./dist/test.js --no-builtins --insert-global-vars="__filename,__dirname" --no-browser-field --dg
$ node ./dist/test.js --version
```

**Comment by MellowMelon** [comment] 2016-06-07 18:10
This looks like a more serious issue that browserify may not be able to directly help you with. There are some dependencies in your bundle, like [UglifyJS](https://github.com/mishoo/UglifyJS2/blob/master/tools/node.js), which are using node filesystem methods to load and execute their own internal dependencies. (I don't claim to understand why it's doing this.) The presence of this code prevents having a single bundled file that can be run on its own. It's way outside the scope of browserify to detect and replace it with a suitable equivalent that works in a standalone environment, unfortunately.

If you open the bundled file and search for `__filename` or `__dirname`, you can find all the cases where your bundle is trying to use its location in the filesystem. These variables were what produced the absolute paths you were seeing before.

**Closed** 2018-02-23 13:16 UTC
Labels: repro-please
